### ISSUE TITLE
Uncaught Error: Cannot find module 'livereload'

### ISSUE THREAD

**Issue by tigranpetrossian** [taggon/livereload#23]
Simply trying to install caused this.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [livereload](https://github.com/taggon/livereload) package, v0.4.0

### Stack Trace

Uncaught Error: Cannot find module 'livereload'

```
At module.js:336

Error: Cannot find module 'livereload'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/tigran/.atom/packages/livereload/lib/server.js:19:19)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/tigran/.atom/packages/livereload/lib/livereload.js:17:15)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:250:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:215:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:158:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:170:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:301:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -5:31.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -4:45.7.0 tree-view:toggle-focus (div.terminal-plus.status-bar)
     -4:38.9.0 window:focus-pane-on-right (atom-pane.pane.active)
     -4:35.6.0 application:add-project-folder (atom-pane.pane.active)
     -4:14.9.0 settings-view:open (atom-pane.pane.active)
  4x -1:19.3.0 key-binding-resolver:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:13.7.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  2x -1:04.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:57.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-less, v0.1.8
emmet, v2.3.14
language-htaccess, v0.1.1
language-liquid, v0.4.0
local-history, v3.2.3
terminal-plus, v0.13.1

# Dev
No dev packages
```

**Comment by taggon** [comment]
Atom can't install node's [livereload](https://www.npmjs.com/package/livereload) which my package references. The v0.4.0 has been unpublished. I'll republish the version when I resolve this bug.

**Comment by taggon** [comment]
Resolved.
