### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\michelle\.atom\packages\liverel...

### ISSUE THREAD

**Issue by ErikCohenDev** [taggon/livereload#25]
[Enter steps to reproduce below:]

1.After update I am unable to use LiveReload getting the message that no file ENOENT 

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [livereload](https://github.com/taggon/livereload) package, v0.4.3
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\michelle.atom\packages\livereload\node_modules\livereload\ext\livereload.js'

```
At fs.js:97

Error: ENOENT: no such file or directory, open 'C:\Users\michelle\.atom\packages\livereload\node_modules\livereload\ext\livereload.js'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at Server.requestHandler (C:\Users\michelle\.atom\packages\livereload\node_modules\livereload\lib\livereload.js:204:27)
  at emitTwo (events.js:87:13)
  at Server.emit (events.js:172:7)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:473:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
  at Socket.socketOnData (_http_server.js:324:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:520:20)

```
### Commands

```
     -2:48.8.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:48.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:47.6.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -2:46.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:42.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:42.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:42.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:36.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:17.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:17.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:15.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:12.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:12.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:12 core:save (atom-text-editor.editor.is-focused)
     -2:05.2.0 livereload:toggle (atom-text-editor.editor.is-focused)
     -0:42 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
atom-jshint, v2.0.0
atom-ternjs, v0.8.4
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.14
esformatter, v1.14.1
git-control, v0.4.0
git-log, v0.4.1
highlight-line, v0.11.0
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
linter, v1.10.0
linter-csslint, v1.1.0
linter-eslint, v4.0.0
linter-js-standard, v3.2.1
livereload, v0.4.3
open-in-browser, v0.4.6
project-manager, v2.6.5
save-session, v0.15.7
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by taggon** [comment]
Hmm... weird. Because I've replaced the livereload node package with my own implementation, my package never load it.
Could you remove my package then reinstall it?
Let me know if your problem still exists.

**Comment by cohenpts** [comment]
Removed and reinstalled @taggon still having the same issue.
Thanks for the fast response.
