### ISSUE TITLE
Uncaught Error: watch ENOSPC

### ISSUE THREAD

**Issue by kameleon83** [taggon/livereload#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: "Manjaro Linux"
**Thrown From**: [livereload](https://github.com/taggon/livereload) package, v0.4.4

### Stack Trace

Uncaught Error: watch ENOSPC

```
At events.js:141

Error: watch ENOSPC
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1247:11)
    at Object.fs.watch (fs.js:1273:11)
    at createFsWatchInstance (/home/sam/.atom/packages/livereload/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sam/.atom/packages/livereload/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sam/.atom/packages/livereload/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/sam/.atom/packages/livereload/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/sam/.atom/packages/livereload/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:34.4.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:33.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  2x -0:26.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.7.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  4x -0:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:12.3.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:11.4.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:08.9.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:08.1.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:06.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:05.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "livereload": {
    "applyImageLive": true,
    "exts": "html, css, js, png, gif, jpg, php, php5, py, rb, erb, coffee, scss"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
browser-plus, v0.0.54
color-picker, v2.1.1
compass, v0.9.1
emmet, v2.4.1
go-plus, v3.5.4
linter, v1.11.3
livereload, v0.4.4
preview-plus, v1.2.6
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by mjerem34** [comment]
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

----------------------------------------------------------------------
Thanks jonshf for your comments.

After doing some research found the solution. Run the below command.

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sys`

**Comment by taggon** [comment]
@mjerem34 Thanks!
