### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/mn/4rtwczv15y31_y6...

### ISSUE THREAD

**Issue by krandis** [taggon/livereload#53]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [livereload](https://github.com/taggon/livereload) package 0.4.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat '/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at realpathSync (fs.js:1542:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:331:24)
    at toRealPath (module.js:130:13)
    at tryFile (module.js:126:22)
    at tryExtensions (module.js:138:22)
    at Function.Module._findPath (module.js:190:20)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom%202.app/Contents/Resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at Object.get [as clipboard] (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/electron.asar/common/api/exports/electron.js:9:18)
    at Object.<anonymous> (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/safe-clipboard.js:2:140)
    at Object.<anonymous> (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/safe-clipboard.js:4:4)
    at Object.<anonymous> (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/safe-clipboard.js:8:3)
    at Module.get_Module._compile (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom%202.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/static/<embedded>:96:26)
    at get__safeClipboard (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/clipboard.js:28:51)
    at get__safeClipboard2 (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/clipboard.js:34:76)
    at Clipboard.write (/private/var/folders/mn/4rtwczv15y31_y6s5nqyrqlw0000gn/T/AppTranslocation/24DB29EC-B77D-4E1B-A52D-9259ABB7FF6D/d/Atom 2.app/Contents/Resources/app/src/clipboard.js:86:13)
    at HTMLElement.handleClick (/packages/livereload/lib/livereload-view.js:48:22)
    at /packages/livereload/lib/livereload-view.js:11:61)
```

### Commands

```
     -0:21.7.0 atom-live-server:startServer (input.hidden-input)
     -0:13.8.0 symbols-view:toggle-project-symbols (input.hidden-input)
     -0:09.9.0 livereload:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
livereload 0.4.4 
```

**Comment by taggon** [comment]
Thanks for the report. I will take a look.
