### ISSUE TITLE
Uncaught TypeError: Cannot read property 'withFileTypes' of null

### ISSUE THREAD

**Issue by planketsoftdev** [taggon/livereload#70]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 ia32
**Electron**: 9.4.4
**OS**: Microsoft Windows 7 Super Lite 
**Thrown From**: [livereload](https://github.com/taggon/livereload) package 0.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'withFileTypes' of null

```
At electron/js2c/asar.js:597

TypeError: Cannot read property 'withFileTypes' of null
    at fs.readdir (electron/js2c/asar.js:597:19)
    at /packages/livereload/node_modules/graceful-fs/graceful-fs.js:201:14)
    at Object.readdir (/packages/livereload/node_modules/graceful-fs/graceful-fs.js:198:12)
    at readdirRec (/packages/livereload/node_modules/readdirp/readdirp.js:210:8)
    at /packages/livereload/node_modules/readdirp/readdirp.js:281:5
    at electron/js2c/asar.js:349:13
    at LOOP (fs.js:1635:14)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.3.0 
K-Syntax 2.0.0 
livereload 0.4.4 
```

**Comment by planketsoftdev** [comment]
please help me.tanks
