### ISSUE TITLE
Uncaught Error: not opened

### ISSUE THREAD

**Issue by kpgarrod** [taggon/livereload#8]
I'm not sure what caused this, but I was switching git branches at the time.

**Atom Version**: 0.191.0
**System**: Mac OS X 10.10.3
**Thrown From**: [livereload](https://github.com/taggon/livereload) package, v0.2.0

### Stack Trace

Uncaught Error: not opened

```
At /Users/admin/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/node_modules/ws/lib/WebSocket.js:175

Error: not opened
  at WebSocket.send (/Users/admin/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/node_modules/ws/lib/WebSocket.js:175:16)
  at WebSocket.write (/Users/admin/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/lib/protocols/hybi.js:101:13)
  at WebSocket.Socket.send (/Users/admin/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/lib/socket.js:106:8)
  at Server.refresh (/Users/admin/.atom/packages/livereload/node_modules/livereload/lib/livereload.js:169:30)
  at StatWatcher.<anonymous> (/Users/admin/.atom/packages/livereload/node_modules/livereload/lib/livereload.js:146:26)
  at emitTwo (events.js:87:13)
  at StatWatcher.emit (events.js:169:7)
  at StatWatcher._handle.onchange (fs.js:1282:10)

```

### Commands

```
     -7:28.0 core:save (atom-text-editor.editor)
     -6:37.2 core:backspace (atom-text-editor.editor)
  2x -6:34.3 core:save (atom-text-editor.editor)
     -5:32.0 editor:duplicate-lines (atom-text-editor.editor)
     -5:15.4 core:move-right (atom-text-editor.editor)
  3x -5:14.8 core:move-left (atom-text-editor.editor)
  2x -4:39.6 editor:newline (atom-text-editor.editor)
     -4:29.9 core:copy (atom-text-editor.editor)
  2x -4:22.7 editor:newline (atom-text-editor.editor)
     -4:19.0 core:paste (atom-text-editor.editor)
  5x -4:17.3 core:backspace (atom-text-editor.editor)
     -4:01.5 core:copy (atom-text-editor.editor)
     -3:45.1 core:paste (atom-text-editor.editor)
     -3:43.0 core:save (atom-text-editor.editor)
     -2:46.4 core:backspace (atom-text-editor.editor)
     -2:34.7 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "dracula-theme"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.0
atom-typescript, v2.15.0
atomatigit, v1.2.3
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
dracula-theme, v0.7.6
editorconfig, v0.3.3
linter, v0.12.0
livereload, v0.2.0
project-manager, v1.15.5
sublime-tabs, v0.5.3
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by taggon** [comment]
4d09367488bdb1c7eb312a89e6034fa89c0c031d Fixed.

**Comment by jonleung** [comment]
I still seem to have this error:

![image](https://cloud.githubusercontent.com/assets/654941/10430630/112cf970-70b5-11e5-967b-27a4a26564cd.png)

This happened when I saved a file.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.3
**Thrown From**: [livereload](https://github.com/taggon/livereload) package, v0.3.3


### Stack Trace

Uncaught Error: not opened

```
At /Users/jon/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/node_modules/ws/lib/WebSocket.js:175

Error: not opened
  at WebSocket.send (/Users/jon/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/node_modules/ws/lib/WebSocket.js:175:16)
  at WebSocket.write (/Users/jon/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/lib/protocols/hybi.js:101:13)
  at WebSocket.Socket.send (/Users/jon/.atom/packages/livereload/node_modules/livereload/node_modules/websocket.io/lib/socket.js:106:8)
  at Server.refresh (/Users/jon/.atom/packages/livereload/node_modules/livereload/lib/livereload.js:179:30)
  at StatWatcher.<anonymous> (/Users/jon/.atom/packages/livereload/node_modules/livereload/lib/livereload.js:154:30)
  at emitTwo (events.js:92:20)
  at StatWatcher.emit (events.js:172:7)
  at StatWatcher._handle.onchange (fs.js:1295:10)

```

### Commands

```
     -0:49.7.0 markdown-writer:insert-link (atom-text-editor.editor.is-focused)
     -0:49.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:43.6.0 markdown-writer:insert-link (atom-text-editor.editor.is-focused)
     -0:43.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:42.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.8.0 markdown-writer:insert-link (atom-text-editor.editor.is-focused)
     -0:32.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:32.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.4.0 markdown-writer:insert-link (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:13.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:04.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "livereload": {
    "exts": ".md"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-text-transformer, v0.7.0
livereload, v0.3.3
markdown-folder, v0.3.1
markdown-table-formatter, v2.5.3
markdown-writer, v2.0.1
sequential-command, v0.3.0
soft-wrap-indicator, v0.7.0
title-case, v0.4.0

# Dev
No dev packages
```
