### ISSUE TITLE
Failed to load the livereload package

### ISSUE THREAD

**Issue by kpgarrod** [taggon/livereload#9]
[Enter steps to reproduce below:]

1. Upgrade Atom to 0.196.0
2. Restart the editor

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [livereload](https://github.com/taggon/livereload) package, v0.2.0

### Stack Trace

Failed to load the livereload package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/admin/.atom/packages/livereload/lib/livereload-view.coffee:4:199)
    at /Users/admin/.atom/packages/livereload/lib/livereload-view.coffee:13:5
    at Object.<anonymous> (/Users/admin/.atom/packages/livereload/lib/livereload-view.coffee:106:5)
    at Object.<anonymous> (/Users/admin/.atom/packages/livereload/lib/livereload-view.coffee:108:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/admin/.atom/packages/livereload/lib/livereload.coffee:4:20)
    at Object.<anonymous> (/Users/admin/.atom/packages/livereload/lib/livereload.coffee:24:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "sublime-tabs",
      "atomatigit",
      "autocomplete-paths",
      "autocomplete-html",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-xml",
      "dev-live-reload",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-toml",
      "project-manager",
      "color-picker",
      "jumpy",
      "linter",
      "linter-tslint",
      "angularjs",
      "language-c",
      "language-clojure"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs-styleguide-snippets, v0.7.0
atom-typescript, v4.1.0
autocomplete-plus, v2.12.1
editorconfig, v1.0.0
emmet, v2.3.8
linter, v0.12.1
livereload, v0.2.0

# Dev
No dev packages
```

**Comment by taggon** [comment]
4d09367488bdb1c7eb312a89e6034fa89c0c031d Fixed.
